#!/usr/bin/expect

set timeout 1000
set email "$env(METEOR_EMAIL)"
set password "$env(METEOR_PASSWORD)"

cd meteor-app

spawn meteor login

expect -- "*Username: "
send "$email\n"
expect -- "*assword: "
send -- "$password\n"
expect -- "*Logged in as*"

spawn meteor deploy --delete $env(METEOR_DEPLOY_URL)
expect -- "Deleted."

spawn meteor deploy $env(METEOR_DEPLOY_URL) --settings settings.json
expect -- "*Now serving at $env(METEOR_DEPLOY_URL)"
